torch.save(ag1,'RESULTS/ag1_'+str(simid)+'.pt')
torch.save(Rtrain,'RESULTS/Rtrain_'+str(simid)+'.pt')
torch.save(Rval,'RESULTS/Rval_'+str(simid)+'.pt')
torch.save(L,'RESULTS/L_'+str(simid)+'.pt')
torch.save(T,'RESULTS/T_'+str(simid)+'.pt')
torch.save(RT,'RESULTS/RT_'+str(simid)+'.pt')
torch.save(ytrain,'RESULTS/ytrain_'+str(simid)+'.pt')
torch.save(yval,'RESULTS/yval_'+str(simid)+'.pt')
torch.save(time,'RESULTS/time_'+str(simid)+'.pt')

torch.save(TRAIN_MAXS,'RESULTS/TRAIN_MAXS_'+str(simid)+'.pt')
torch.save(TRAIN_INDS,'RESULTS/TRAIN_INDS_'+str(simid)+'.pt')

torch.save(VAL_MAXS,'RESULTS/VAL_MAXS_'+str(simid)+'.pt')
torch.save(VAL_INDS,'RESULTS/VAL_INDS_'+str(simid)+'.pt')
